title: Welcome to the Water Tribe
author: Victor-Nyagudi
email: heightabovesealevel@gmail.com
theme: minima

description: > # this means to ignore newlines until "baseurl:"
  This is a short description that will appear in the head of my document for Google searches.
  Again, not much to say here. Just adding it as per the instructions given to me.

# social links
twitter_username: Vicktor_Oti # DO NOT include the @ character, or else the build will fail!
github_username:  Victor-Nyagudi # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
